### ISSUE TITLE
expose an example standalone function

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#10]
We don't always need to functions to exist as full object constructors (i.e. `var waka = new Flocka()`. Let's put together an example of a module that is just a standalone function.

**Comment by GretaCB** [comment]
Per chat:
- In vt-shaver, we implemented a standalone function, which is more performant because you dont need to create individual object instances for each use. It's a micro-optimization since object instances require an allocation and garbage collection to track them. We're preventing V8 from having to do unnecessary work.
- Build a standalone hello-world function as "hello-world.cpp" as default, and move current code into hello_world_class.cpp

**Comment by mapsam** [comment]
Looking at nodejs's example repo, they have it structured for different types of javascript functionality: https://github.com/nodejs/node-addon-examples

**Comment by GretaCB** [comment]
All set per https://github.com/mapbox/node-cpp-skel/pull/44
