### ISSUE TITLE
Check in package-lock.json or no?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp-skel#124]
My (limited) understanding is that we only want to version `package-lock.json` inside a git repo at an "end-of-line" or final dependency where we want to control versions tightly. For something like `node-cpp-skel` we don't want to check in `package-lock.json`. What do others think?

/cc @millzpaugh @mapsam @GretaCB 

Asking since:

 - We do not currently have `package-lock.json` in the `.gitignore`
 - I noticed @millzpaugh checked it in for node-cpp-skel at https://github.com/mapbox/node-cpp-skel/commit/e829302241dc528df86681b12f0190088a235bf3#diff-32607347f8126e6534ebc7ebaec4853d

@millzpaugh was this intended?

**Comment by jfirebaugh** [comment]
If npm+package-lock.json works the same as yarn+yarn.lock (and I imagine it does), then the lockfile takes effect only when you're running `npm install` within the package repository, for development of the package itself. When the package is listed as a dependency in some downstream package or application, it's own lockfile is ignored. This implies two things:

* When you want control over which versions of your dependencies get installed when your package is itself used as a dependency, that must go in package.json.
* There's [a convincing argument that lockfiles should always be checked in](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/).

**Comment by springmeyer** [comment]
Here are my thoughts:

 - I'm appreciative of both @jfirebaugh and @mapsam sharing context and knowledge
 - I'm 👍  keeping the lockfile checked in for now
 - I personally need to take some time to digest the linked docs to get familiar/comfortable with lockfiles
 - I'll do that in about ~ month when I'm back from vacation and will re-open this ticket if I have further questions or concerns.

**Comment by allieoop** [comment]
I agree with the [convincing argument that lockfiles should always be checked in](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) and @mapsam's [comment](https://github.com/mapbox/node-cpp-skel/issues/124#issuecomment-384817201) about the 2 big reasons package-lock.json should be included. 

And since npm will always ignore this file when publishing I don't see any downside to including it. Or is the problem that only npm v5.x and above will ignore it when packing and publishing? For example, if we are building node-cpp-skel using node v4.8.4 (npm v2.15.11) and it has a package-lock.json file, is it not ignored? And what is the harm in it being part of the build, besides maybe a waste of space?

**Comment by millzpaugh** [comment]
@allieoop great point re npm versions and whether or not they ignore the package-lock.json. 

@springmeyer sorry I must have missed this back in April - I committed the package-lock file because I thought it was a best practice for the reasons @mapsam listed. Thanks for kickstarting this conversation.

**Comment by mapsam** [comment]
@allieoop good point about publishing a package using NPM v2 (likely Node.js v4) that has a package-lock.json present! I just tested this out with a sample package `mapsam-testing-npm`. I published two versions: 

* `0.1.0` published with NPM v2 and a package-lock.json file - it ships with a package-lock.json file (this is probably expected, since NPM v2 doesn't know to ignore the lockfile)
* `0.2.0` published with NPM v6 and a package-lock.json file - it _does not_ ship with a lockfile (also expected per NPM documentation noted above)

This is an interesting case, one where a lockfile may be committed. That said, I don't see this being too harmful. If we _do_ think this is harmful, I'd suggest it's a great reason and opportunity to completely avoid NPM v2 at this point, and move to the latest v5 or v6 and upgrade node versions to >=6 locally and in applications. We should avoid publishing with NPM v2, especially if a module has already been published with NPM >=5 and has a package-lock.json file.

**Comment by springmeyer** [comment]
closing again.

> seen some narly consequences of package-lock.json being checked in and how it relates to modules using node-pre-gyp to bundle deps

This is still true, but hopefully I've solved this now. During https://github.com/mapbox/core-tech/issues/381 I stopped using `bundledDeps` which should avoid this problem. The other workaround I've used is to install with the same version of `npm` that was used to bundle the deps, but that is impossible to control.

Next action is to update the node-pre-gyp readme to remove the mention/requirement of bundlingDeps since as long as you drop support for node v0.10, the bundledDeps approach should not be required. The idea is that node-pre-gyp should work without bundledDeps as long as npm installs it predictably first, before trying to build the specific module and as long as npm predictably dedupes `node-pre-gyp` while keeping it on PATH. These conditions seem true in testing so far and node-sqlite3 has been out for several weeks without problems after unbundling.

So, back to getting used to package-lock.json without being totally blocked by it.

**Comment by springmeyer** [comment]
> The idea is that node-pre-gyp should work without bundledDeps as long as npm installs it predictably first

-> https://github.com/mapbox/node-cpp-skel/pull/148

**Comment by GretaCB** [comment]
Posting Platform team's npm/package-lock best practices doc here for future reference: https://github.com/mapbox/platform/blob/master/docs/reference/nodejs-recommendations.md#using-npm-packagejson-and-package-lockjson

> install with the same version of npm that was used to bundle the deps, but that is impossible to control

Thank you for this validation @springmeyer . I was also doing the same, and it was maddening to attempt to remember and keep this consistent throughout the dev process, especially when multitasking and working on different projects.
