### ISSUE TITLE
Create a branch without magic NAN macros, as recommended in newer docs

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#17]
Per chat with @mikemorris @springmeyer @GretaCB - there are some new approaches to working with NAN that remove the usage of magic macros like `NAN_METHOD`. Let's create a branch with [information from this blog post](https://nodesource.com/blog/c-add-ons-for-nodejs-v4/) and see what it looks like!

**Comment by GretaCB** [comment]
Thoughts:
- NAN best practices
- Add benchmark to measure differences with how we're using NAN
- relevant to adding benchmarks to skel in general, move on this ticket once we have benchmark scaffolding in skel

**Comment by mikemorris** [comment]
> NAN best practices

👍 would be great to document these and and use them more consistently across projects

> Add benchmark to measure differences with how we're using NAN

For the most part removing the NAN macros should be just a superficial change. After compiling everything it should be the exact same code running, it should just be more obvious where a `Nan::FunctionCallbackInfo<v8::Value>& info` comes from instead of it "magically" existing inside a function.

**Comment by springmeyer** [comment]
Great, @mikemorris - is this something you could hit?

**Comment by springmeyer** [comment]
wrapped up per https://github.com/mapbox/node-cpp-skel/pull/33#issuecomment-319523526
