### ISSUE TITLE
General CI conventions for travis/bitrise/circleci

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#20]
Per @mikemorris's comment:

> I rigged up [a script to only publish on git tags](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/scripts/after_script.sh) for mapbox-gl-native, but unfortunately it doesn't support Bitrise, as it relies on the [`TRAVIS_TAG`](https://github.com/mapbox/mapbox-gl-native/blob/master/.travis.yml#L68) environment variable. Figuring out some convention that works across Travis CI, Bitrise and Circle CI here would be great.

This would be rad.

**Comment by springmeyer** [comment]
First let's get other ci working. So first actions are #23 and #24

**Comment by springmeyer** [comment]
I'm comfortable sticking with the 'commit message to publish' since, as mentioned, hooking into tags is ci platform specific. Mapbox GL Native does auto-publishing on tags and this recently broke and was tricky to fix when moving from travisci to circle. So, I'm going to close this as non-actionable with the additional thought that downstream developers could implement this but it currently feels out of scope for node-cpp-skel.
